### PR TITLE
Compute qName once we've filled in the local array.

### PR DESCRIPTION
**Pull request by emilio**
Since it depends on it.

Fixes #91

### CODE REVIEW

**Comment by emilio** [comment]
@sideshowbarker can you confirm this fixes the issue you're seeing?

**Comment by emilio** [comment]
Build failures seem unrelated

**Comment by emilio** [comment]
cc @hsivonen

**Comment by sideshowbarker** [comment]
> @sideshowbarker can you confirm this fixes the issue you're seeing?

Yeah, it does (and thanks much)

**Review by sideshowbarker — APPROVED** [review]
Will wait to merge until @hsivonen has also reviewed

**Review by hsivonen — APPROVED** [review]
Thanks! How has this ever worked at all?

**Pull request merged**
