### PR TITLE
Mozilla bug 1701828 - Meta charset rewrite for Gecko.

### PR DESCRIPTION
**Pull request by hsivonen**
Differential Revision: https://phabricator.services.mozilla.com/D125808

### CODE REVIEW

**Comment by hsivonen** [comment]
Added more documentation comments.

**Comment by sideshowbarker** [comment]
Going ahead and merging here, on the assumption that any review comments @smaug---- might have could be addressed in a follow-up commit.

**Comment by smaug----** [comment]
@hsivonen might have added some more comments to the code in mozilla-central, not sure.

**Comment by hsivonen** [comment]
Thanks for merging. Yeah, I forget to push the last round of added comments. I opened a [new PR](https://github.com/validator/htmlparser/pull/64) for them.

**Pull request merged**
